// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nao1215/sqluv/config"
	"github.com/nao1215/sqluv/infrastructure/persistence"
	"github.com/nao1215/sqluv/interactor"
	"github.com/nao1215/sqluv/tui"
)

// Injectors from wire.go:

// New creates a new sqluv command instance.
func NewSqluv(arg *config.Argument) (*tui.TUI, error) {
	csvReader := persistence.NewCSVReader()
	tsvReader := persistence.NewTSVReader()
	ltsvReader := persistence.NewLTSVReader()
	fileReader := interactor.NewFileReader(csvReader, tsvReader, ltsvReader)
	tuiTUI := tui.NewTUI(arg, fileReader)
	return tuiTUI, nil
}
