// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nao1215/sqluv/config"
	"github.com/nao1215/sqluv/infrastructure/memory"
	"github.com/nao1215/sqluv/infrastructure/persistence"
	"github.com/nao1215/sqluv/interactor"
	"github.com/nao1215/sqluv/tui"
)

// Injectors from wire.go:

// New creates a new sqluv command instance.
func NewSqluv(arg *config.Argument) (*tui.TUI, func(), error) {
	csvReader := persistence.NewCSVReader()
	tsvReader := persistence.NewTSVReader()
	ltsvReader := persistence.NewLTSVReader()
	fileReader := interactor.NewFileReader(csvReader, tsvReader, ltsvReader)
	memoryDB, cleanup, err := config.NewMemoryDB()
	if err != nil {
		return nil, nil, err
	}
	tableCreator := memory.NewTableCreator(memoryDB)
	usecaseTableCreator := interactor.NewTableCreator(tableCreator)
	queryExecutor := memory.NewQueryExecutor(memoryDB)
	statementExecutor := memory.NewStatementExecutor(memoryDB)
	sqlExecutor := interactor.NewSQLExecutor(queryExecutor, statementExecutor)
	recordsInserter := memory.NewRecordInserter(memoryDB)
	usecaseRecordsInserter := interactor.NewRecordsInserter(recordsInserter)
	dbConfig, err := config.NewDBConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	historyDB, cleanup2, err := config.NewHistoryDB(dbConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	historyTableCreator := persistence.NewHistoryTableCreator(historyDB)
	usecaseHistoryTableCreator := interactor.NewHistoryTableCreator(historyTableCreator)
	historyCreator := persistence.NewHistoryCreator(historyDB)
	usecaseHistoryCreator := interactor.NewHistoryCreator(historyCreator)
	historyLister := persistence.NewHistoryLister(historyDB)
	usecaseHistoryLister := interactor.NewHistoryLister(historyLister)
	tuiTUI := tui.NewTUI(arg, fileReader, usecaseTableCreator, sqlExecutor, usecaseRecordsInserter, usecaseHistoryTableCreator, usecaseHistoryCreator, usecaseHistoryLister, dbConfig)
	return tuiTUI, func() {
		cleanup2()
		cleanup()
	}, nil
}
